[IDENTIFICATION]
USERAGENT = IR US26 12387685, 10707561, 95325188

[CONNECTION]
HOST = styx.ics.uci.edu
PORT = 9000

[CRAWLER]
SEEDURL = https://www.ics.uci.edu,https://www.cs.uci.edu,https://www.informatics.uci.edu,https://www.stat.uci.edu
# Measured in seconds
POLITENESS = 0.5

[LOCAL PROPERTIES]
# Save file for crawler progress
SAVE = frontier.shelve

# IMPORTANT: DO NOT CHANGE IT IF YOU HAVE NOT IMPLEMENTED MULTITHREADING.
THREADCOUNT = 4

